//------------------------------------------------------------------------
// Copyright(c) 2023 Oberon Day-West.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"delay2.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"delay2 VST3 (64Bit)"
#else
#define stringFileDescription	"delay2 VST3"
#endif
#define stringCompanyName		"Oberon Day-West\0"
#define stringLegalCopyright	"Copyright(c) 2023 Oberon Day-West."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
